class Locators:
    FIRST_NAME = "input[placeholder='First Name']"
    LAST_NAME = "input[placeholder='Last Name']"
    ADDRESS = "textarea[ng-model='Adress']"
    EMAIL = "input[type='email']"
    PHONE = "input[type='tel']"
    GENDER_MALE = "input[value='Male']"
    GENDER_FEMALE = "input[value='FeMale']"
    HOBBIES_CRICKET = "input[value='Cricket']"
    HOBBIES_MOVIES = "input[value='Movies']"
    HOBBIES_HOCKEY = "input[value='Hockey']"
    LANGUAGES_DROPDOWN = "div#msdd"
    GENERIC_LANGUAGE_ENTITY = "li:has-text('{}')"
    SKILLS_DROPDOWN = "select#Skills"
    COUNTRY_DROPDOWN = "select#country"
    YEAR_DROPDOWN = "select#yearbox"
    MONTH_DROPDOWN = "select[ng-model='monthbox']"
    DAY_DROPDOWN = "select#daybox"
    PASSWORD = "input#firstpassword"
    CONFIRM_PASSWORD = "input#secondpassword"
    SUBMIT_BUTTON = "button#submitbtn"